version: '3.9'
services:
  db:
    container_name: postgress-library
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  - ${TYPEORM_DATABASE}:${TYPEORM_DATABASE}
